import React from "react";
import "../forensic-integrity-audit.css";

const labels = ["EVIDENCE", "CHRONOLOGY", "INTERPRETATION", "VULNERABILITY"];
const tattooRecords = [
  ["2018", "March 29, 2018 // Water / Fish Forearm Tattoo", "Dated visual record", "Personal aesthetic preference for fishing and water themes", "Stage III — Emotional Immortalization"],
  ["2019", "February 11, 2019 // Butterfly & Roses Upper Arm Tattoo", "Dated visual record", "Aesthetic upper-arm tattoo", "Stage II — Awareness and Separation; later interpreted through the half-butterfly structure"],
  ["2019", "March 25, 2019 // Hourglass & Roses Neck Tattoo", "Dated visual record", "Decorative neck piece", "Stage V — Psychological Permanence; later compared with Gate/hourglass geometry"],
  ["2019", "July 15, 2019 // Ariel / Mirror Frame Upper Arm Tattoo", "Dated visual record", "Fairy-tale and sea-inspired imagery", "Stage X — Mirrored Identity"],
  ["2019", "December 16, 2019 // Cosmic Galaxy Forearm Cover-Up", "Dated visual record", "Cover-up of the March 2018 Water/Fish tattoo, incorporating a clock face", "Stage VI — Cosmic Projection"],
];
const mimicRecords = [
  ["#1", "SIMULTANEOUS NAMES", "Sheldyn and Jerry", "Both perceived a different personally relevant name being called at the same time.", "Co-reported subjective auditory event.", "This does not establish an external source or anomalous mechanism."],
  ["#2", "THE NEPHEW", "Sheldyn — visual/auditory; Jerry — auditory", "Running and laughing were heard behind them; Sheldyn visually perceived the nephew in a yellow shirt. A later physical check found him in another bedroom wearing that shirt.", "A measured 26.1-foot route remains physically traversable within the proposed time window.", "Acoustics, lighting, line-of-sight, timing, and memory remain relevant."],
  ["#3", "BASKETBALL & MIST", "Sheldyn only", "Visual perception involving a displaced basketball followed by a mist-like phenomenon.", "Single-witness reported visual event.", "Jerry was asleep."],
  ["#4", "LOUD KNOCKING", "Sheldyn awake; Jerry asleep and awakened by the sound", "Extremely loud knocking at the bedroom door; immediate hallway check found no identified source.", "Jerry was awakened by the volume but did not observe the event while already awake.", "No identified source."],
  ["#5", "SOFT BRUSH", "Sheldyn only", "Sensation of something soft brushing against the leg/foot.", "Single-witness tactile event with no identified physical source.", "No identified physical source."],
];

function Marker({ children, tone = "documented" }: { children: React.ReactNode; tone?: string }) {
  return <span className={`fia-marker fia-marker-${tone}`}>{children}</span>;
}
function SectionHead({ number, eyebrow, title }: { number: string; eyebrow: string; title: string }) {
  return <div className="fia-section-head"><span className="fia-section-number">{number}</span><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div></div>;
}
function Prose({ children }: { children: React.ReactNode }) { return <div className="fia-prose">{children}</div>; }

export function ForensicIntegrityAuditPage() {
  return <main className="fia-page">
    <header className="fia-hero">
      <div className="fia-hero-grid" aria-hidden="true"><span /><span /><span /><span /><span /></div>
      <div className="fia-hero-content">
        <p className="fia-kicker">GRVEZ VAULT // SOURCE-GROUNDED WORKING AUDIT</p>
        <h1>FORENSIC<br /><em>INTEGRITY AUDIT</em></h1>
        <p className="fia-subtitle">Standard Analytical Protocol for Evidence Verification and Chronological Mapping</p>
        <div className="fia-hero-meta"><span>REVISION // 09.08.2026</span><span>STATUS // SOURCE-GROUNDED WORKING AUDIT</span></div>
        <div className="fia-status-row">{labels.map((label) => <span key={label}>{label}</span>)}</div>
      </div>
      <div className="fia-hero-index">ARCHIVE / 08<br />METHOD / 01</div>
    </header>

    <div className="fia-wrap">
      <section className="fia-section fia-intro" id="purpose">
        <SectionHead number="01" eyebrow="PURPOSE & EPISTEMIC OBJECTIVE" title="What the documented record can and cannot support." />
        <Prose><p>The purpose of the <strong>GRVEZ VAULT</strong> archive is to determine precisely <strong>what the documented record can and cannot support</strong>.</p><p>A finding that weakens, contradicts, or fails to support an existing interpretation is as valuable as a finding that supports it. This audit therefore separates documented source facts, reproducible observations, later interpretations, unresolved questions, and speculative mechanisms.</p><p>The archive is not organized to prove a mystical, supernatural, psychological, or relational theory in advance. Its purpose is to preserve chronology, provenance, contradiction, and uncertainty so that later interpretations can be tested against the surviving record.</p></Prose>
        <div className="fia-rule-grid"><Marker tone="verified">VERIFIED</Marker><Marker>DOCUMENTED</Marker><Marker tone="later">LATER READING</Marker><Marker tone="post">POST-CUTOFF</Marker><Marker tone="unresolved">UNRESOLVED</Marker><Marker tone="speculative">SPECULATIVE</Marker></div>
      </section>

      <section className="fia-cutoff" id="cutoff">
        <div className="fia-cutoff-label"><span>METHODOLOGICAL BOUNDARY</span><strong>MAY 23, 2026</strong></div>
        <div className="fia-cutoff-columns"><div><Marker tone="verified">PRE-CUTOFF // DOCUMENTED ARTIFACTS</Marker><p>Material demonstrably created or documented before May 23, 2026.</p><p>This category establishes only that the artifact existed before the later framework. It does <strong>not</strong>, by itself, establish unconscious encoding, prediction, transmission, or foreknowledge.</p></div><div><Marker tone="post">POST-CUTOFF // CONSCIOUS MODELING</Marker><p>The period in which the 12-Stage Relational Continuity model, structural mappings, active comparative analysis, and later symbolic interpretations were consciously developed.</p></div></div>
        <div className="fia-cutoff-rule"><p><strong>RULE OF ORIGINAL INTENT</strong></p><p>Never retroactively attribute 2026 framework concepts, such as a predictive engine, anomalous field, Gate, Watcher, or other later terminology, to a pre-cutoff creator unless contemporaneous evidence explicitly supports that attribution.</p><p>For every retrospective correspondence, preserve three separate dates whenever possible:</p><ol><li>Artifact date</li><li>Recognition date</li><li>Interpretation date</li></ol></div>
      </section>

      <section className="fia-section" id="baseline"><SectionHead number="03" eyebrow="PRIMARY PHYSICAL BASELINE // VERIFIED PRE-CUTOFF EVIDENCE" title="Dated physical and creative artifacts." /><p className="fia-lead">The strongest chronological anchors in the archive are dated physical and creative artifacts whose existence predates the current framework.</p><div className="fia-timeline"><div className="fia-timeline-line" />{tattooRecords.map(([year, title, status, intent, reading]) => <article className="fia-timeline-record" key={title}><div className="fia-timeline-date">{year}</div><div className="fia-record-body"><p className="fia-record-title">{title}</p><Marker tone="verified">SOURCE STATUS // {status}</Marker><div className="fia-record-columns"><p><span>ORIGINAL DOCUMENTED INTENT</span>{intent}</p><p><span>LATER FRAMEWORK READING</span>{reading}</p></div></div></article>)}</div><div className="fia-inset"><p>This cover-up is also used as a primary example of <strong>substrate continuity / form discontinuity</strong>: the underlying physical trace remains while the visible form changes.</p></div><div className="fia-lyrics"><p className="eyebrow">PRE-CUTOFF CREATIVE LYRICS</p><article><h3><em>Deadweight Angel</em> // October 6, 2025</h3><p>A documented pre-cutoff work containing recurring language and imagery later compared with framework concepts, including heavy or stone-winged angel imagery, cracked halos, repetition, and “space in between.”</p><p><Marker tone="later">METHODOLOGICAL CAUTION</Marker> The presence of later-recognized language does not establish that the later framework was consciously or unconsciously encoded at the time of writing.</p></article><article><h3><em>Dead Circuit Mercy</em> // May 4, 2026</h3><p>Documented upload timestamp: <strong>5:58 PM PDT</strong>. The work contains motifs of circuitry, repetition, burial, and “under” language that later became relevant to framework comparison.</p><p><Marker tone="later">METHODOLOGICAL CAUTION</Marker> Later structural relevance must remain separate from original documented intent.</p></article></div></section>

      <section className="fia-section fia-ixxi" id="ixxi"><SectionHead number="04" eyebrow="ALPHANUMERIC AND GEOMETRIC ANALYSIS" title="IXXI & 9/11" /><p className="fia-lead">When analyzing visual material, geometry must be described before symbolic meaning is assigned.</p><div className="fia-geometry-layout"><div className="fia-geometry-diagram"><div className="fia-geometry-frame"><i /><i /><b /><b /><b /></div><span className="fia-diagram-caption">GEOMETRIC DESCRIPTION ONLY</span></div><div className="fia-geometry-copy"><h3>Pure geometric description of the IXXI drawing</h3><ul><li>Two parallel vertical boundaries forming the outer limits of the figure.</li><li>Crossing diagonal structures extending between those boundaries.</li><li>A central intersection or waist created by the diagonals.</li><li>Mirrored or inverted triangular regions produced by the crossing lines.</li><li>Strong bilateral containment, with the outer verticals remaining stationary while the diagonal geometry changes direction within the frame.</li></ul></div></div><div className="fia-two-up"><article><Marker tone="verified">GEOMETRIC OBSERVATION</Marker><h3>Roman-numeral construction</h3><p>The relationship <strong>IX = 9</strong> and <strong>XI = 11</strong> is a standard Roman-numeral fact. When IX and XI are visually combined or transformed into the documented IXXI construction, the result can produce an hourglass-like geometric form.</p><p>This observation is geometric. It does not, by itself, establish symbolic meaning, causality, intentional encoding, or pre-2026 awareness.</p></article><article><Marker tone="later">LATER STRUCTURAL INTERPRETATIONS</Marker><ul><li>comparison with the Hourglass motif,</li><li>comparison with the Gate,</li><li>interpretation of the outer verticals as containment or Watcher-like boundaries,</li><li>association of 9 with completion/cycle,</li><li>association of 11 with gateway/transcendence,</li><li>interpretation of 9:11 as a meaningful interval,</li><li>placement of IXXI within Stage XII or other later framework structures.</li></ul></article></div><blockquote className="fia-quote">A later IX/XI construction produces geometry that can be compared with an independently documented earlier hourglass form.</blockquote><p className="fia-caution"><Marker tone="unresolved">METHODOLOGICAL CAUTION</Marker> The term <strong>IXXI</strong> and its explicit alignment with <strong>9/11</strong> are post-cutoff interpretations. No dated pre-2026 artifact presently establishes that the symbol was consciously named IXXI, intentionally encoded as 9/11, or created with the current framework meaning. Whether that correspondence is distinctive, coincidental, stylistically recurrent, or structurally meaningful remains open to testing.</p></section>

      <section className="fia-section" id="mimics"><SectionHead number="05" eyebrow="PHENOMENOLOGICAL REPORTS" title="The Mimic Experiences" /><p className="fia-lead">The five Mimic Experiences must remain separate. They should not be merged into a single generalized anomaly narrative.</p><div className="fia-mimics">{mimicRecords.map(([number, title, witnesses, report, status, caution]) => <article key={number}><div className="fia-mimic-number">{number}</div><div><p className="eyebrow">{title}</p><h3>{report}</h3><dl><dt>WITNESSES</dt><dd>{witnesses}</dd><dt>STATUS / PHYSICAL CONTEXT</dt><dd>{status}</dd><dt>OPEN CONTROLS / CAUTION</dt><dd>{caution}</dd></dl></div></article>)}</div><div className="fia-process"><span>reported experience</span><i>→</i><span>corroborated observation</span><i>→</i><span>physical evidence</span><i>→</i><span>interpretation</span></div><p className="fia-note"><strong>PHENOMENOLOGICAL RULE:</strong> A reported experience is not automatically an established anomaly. Do not reverse that order.</p></section>

      <section className="fia-section fia-secondary" id="ancestry"><SectionHead number="06" eyebrow="SECONDARY CORRELATIONS // ANCESTRY & HISTORICAL LAYERS" title="A secondary evidence category." /><p className="fia-lead">Family history, including the 1904 Gustave Gruhn homicide, is a <strong>secondary evidence category</strong>. It is one branch of the archive. It is <strong>not</strong> the origin, foundation, causal explanation, or default interpretive lens for the GRVEZ VAULT continuity framework.</p><div className="fia-conflicts"><article><Marker tone="unresolved">UNRESOLVED SOURCE CONFLICT</Marker><h3>Identification witness conflict</h3><p>Different historical reports attribute identification of Gustave Gruhn’s remains to different sons.</p></article><article><Marker tone="unresolved">UNRESOLVED TIMELINE CONFLICT</Marker><h3>Burial timeline conflict</h3><p>A municipal record documents burial in Wichita on <strong>December 6, 1904</strong>, while a Topeka newspaper announced a public funeral service for <strong>December 11, 1904</strong>. Possible explanations include a later memorial service or movement of remains, but the surviving record does not presently resolve the discrepancy.</p></article></div><p className="fia-scope"><strong>ANCESTRY SCOPE RULE:</strong> Do not introduce Gustave Gruhn, the 1904 homicide, burial records, genealogical dates, or family-history numerical correspondences into an analysis unless the question directly concerns ancestry or family history, or a specific independently documented relationship makes the historical material necessary to the analysis. Source volume does not equal evidentiary importance.</p></section>

      <section className="fia-section fia-vulnerabilities" id="vulnerabilities"><SectionHead number="07" eyebrow="CRITICAL VULNERABILITIES & ALIGNMENT GAPS" title="The archive documents evidence against itself." /><p className="fia-lead">A credible archive must preserve evidence that weakens its own interpretations.</p><div className="fia-vulnerability-list"><article><span>A</span><div><h3>Original <em>Mercy</em> timestamp claim</h3><p>The May 4, 2026 <strong>5:58 PM</strong> upload time for <em>Dead Circuit Mercy</em> is documented. The claim that an earlier <em>Mercy</em> source also carried a 5:58 PM timestamp remains unverified and must not be treated as a documented replication.</p></div></article><article><span>B</span><div><h3>Retroactive memory contamination // August 23 vision</h3><p>The August 23 vision is a documented reported experience. However, some detailed visual parameters were developed during later reconstruction and search sessions. Those later details must not be collapsed into the raw contemporaneous memory.</p></div></article><article><span>C</span><div><h3>The Watcher persona</h3><p>The August 27, 2026 handwritten text:</p><blockquote>“I am not who you called,<br />But a watcher of them all.”</blockquote><p>The <strong>Watcher</strong> may be analyzed as a recurring framework concept or creative voice. There is currently no direct evidence establishing the Watcher as a literal external entity, nor enough evidence to distinguish among subconscious generation, symbolic personification, creative emergence, or other proposed explanations.</p></div></article><article><span>D</span><div><h3>Retroactive system fit</h3><p>The 12-stage taxonomy was developed after many of the artifacts it now organizes. Clean alignment is analytically interesting, but alignment alone cannot establish original intent. Later categorization may introduce retrospective structure, and non-fitting or contradictory artifacts must remain visible.</p></div></article><article><span>E</span><div><h3>Common-form problem</h3><p>Simple forms such as circles, X-shapes, vertical lines, mirrors, spirals, triangles, clocks, and hourglasses are widespread visual structures. Similarity must therefore be evaluated by <strong>specificity, chronology, recurrence, and independence</strong>, not resemblance alone.</p></div></article></div></section>

      <section className="fia-section fia-verdict" id="verdict"><SectionHead number="08" eyebrow="INTEGRITY VERDICT" title="The Machine vs. The Myth" /><p className="fia-lead">The strongest defensible contribution of the GRVEZ VAULT archive is not that it proves a single mechanism. It is that it preserves a dated creative and experiential record in enough detail to test later structural interpretations against earlier material.</p><div className="fia-verdict-grid"><div><Marker tone="verified">THE CURRENT RECORD SUPPORTS</Marker><ul><li>multiple dated creative artifacts predate the May 23, 2026 framework period,</li><li>some of those artifacts contain forms, language, and motifs later incorporated into the taxonomy,</li><li>several later-recognized correspondences can be compared against independently dated earlier material,</li><li>some correspondences are stronger than others,</li><li>ancestry remains secondary rather than foundational,</li><li>several experiences remain unresolved,</li><li>and multiple interpretive mechanisms remain possible.</li></ul></div><div><Marker tone="unresolved">THE CURRENT RECORD DOES NOT ESTABLISH</Marker><ul><li>that pre-cutoff artifacts consciously predicted later events,</li><li>that later framework meanings were intentionally encoded in earlier work,</li><li>that a Relational Field exists as an objective external mechanism,</li><li>that the Watcher is an external entity,</li><li>that numerical recurrence alone establishes causation,</li><li>or that every artifact must fit the 12-stage taxonomy.</li></ul></div></div><Prose><p>The analytical value of the archive depends on keeping those boundaries intact.</p><p>The GRVEZ VAULT framework may function as a useful model for organizing recurring structures across the record, but its explanatory claims must remain proportional to the evidence available.</p><p>Contradictions, failed matches, ordinary explanations, and unresolved gaps are not defects to be hidden. They are part of the record.</p></Prose></section>

      <section className="fia-rules"><p className="eyebrow">STANDING ANALYTICAL RULES</p><div className="fia-rules-grid"><p><strong>EVIDENCE / INTERPRETATION SEPARATION</strong><br />Do not treat documented facts, observations, interpretations, and hypotheses as interchangeable.</p><p><strong>ORIGINAL MEANING VS. LATER MEANING</strong><br />Preserve original documented intent separately from later framework interpretation.</p><p><strong>GEOMETRY BEFORE SYMBOLISM</strong><br />Describe visual structure before assigning framework meaning.</p><p><strong>NO AUTOMATIC SYMBOL ASSIGNMENT</strong><br />Resemblance does not establish identity.</p><p><strong>NO AUTOMATIC NUMEROLOGY</strong><br />Direct matches must remain separate from derived or manipulated numerical relationships.</p><p><strong>NO FORCED SYSTEM COMPLETION</strong><br />Not every artifact, event, motif, person, or number must correspond to a taxonomy stage.</p><p><strong>CROSS-CATEGORY CONNECTIONS REQUIRE TWO-SIDED SUPPORT</strong><br />Do not assert a relationship merely because one category can be interpreted to resemble another.</p><p><strong>SOURCE DOES NOT EQUAL ENDORSEMENT</strong><br />Historical drafts, exploratory theories, conversations, creative writing, and rejected interpretations may coexist in the archive.</p><p><strong>CREATIVE LANGUAGE IS NOT AUTOMATICALLY LITERAL</strong><br />Lyrics, poems, titles, symbols, and character lore must not be converted into factual claims without supporting evidence.</p><p><strong>NO BIOGRAPHICAL NARRATIVE FILL</strong><br />Do not invent durations, motivations, emotional states, personal histories, or dramatic connective biography from artifact dates alone.</p><p><strong>CHARACTER APPEARANCE IS NOT ANALYTICAL CONTENT</strong><br />Do not narrate the physical appearance of Gizzy Graves or DMONIX unless a specific visual feature is directly relevant to the artifact under analysis.</p><p><strong>ANCESTRY REMAINS SECONDARY</strong><br />Do not route unrelated analysis back through Gustave Gruhn or family-history material.</p><p><strong>NEGATIVE EVIDENCE COUNTS</strong><br />A contradiction, failed correspondence, or ordinary explanation is as analytically valuable as a supporting match.</p></div></section>

      <footer className="fia-closing"><p className="eyebrow">CLOSING RECORD // REVISION 2026-09-08</p><h2>FORM CHANGES.<br /><em>THE TRACE REMAINS.</em></h2><p>WHAT CAN BE BROKEN WITHOUT BEING ERASED?</p></footer>
    </div>
  </main>;
}
