import React, { useEffect } from "react";
import { Link } from "react-router-dom";
import { Breadcrumb } from "../Breadcrumb";

function PendingAsset({ label, detail }: { label: string; detail: string }) {
  return <div className="visdoc-asset-pending" role="status"><p className="eyebrow">SOURCE IMAGE PENDING</p><strong>{label}</strong><p>{detail}</p></div>;
}

export function MediaPage() {
  useEffect(() => { document.title = "Visual Documentation | GRVEZ VAULT"; return () => { document.title = "GRVEZ VAULT | Music · Archive · Manuscripts · Media"; }; }, []);
  return <section className="page-section manuscripts-page" aria-labelledby="media-heading"><div className="page-content">
    <Breadcrumb items={[{ label: "Archive", to: "/archive" }, { label: "Visual Documentation" }]} />
    <p className="eyebrow">ARCHIVE RECORD // 003</p><h1 id="media-heading">Visual Documentation</h1>
    <p className="page-description">Artwork. Photography. Symbols. Concept art. Visual evidence preserved and catalogued throughout the archive’s investigation.</p>
    <section className="archive-note"><p className="eyebrow">SOURCE-GROUNDED RESTORATION</p><h2>Evidence separated by status.</h2><p>Original documented artifacts, later interpretation graphics, and unresolved source dependencies are kept visibly distinct. Missing files are never replaced with invented or broken imagery.</p></section>
    <div className="visdoc-tier-label"><p className="eyebrow">ORIGINAL DOCUMENTED ARTIFACTS</p><h2>Primary Evidence</h2></div>
    <Link to="/media/visual-evolution" className="visdoc-exhibit-featured"><img src="/HALF_BUTTERFLY_TATTOO.png" alt="Visual Evolution source compilation" loading="lazy" /><div className="visdoc-exhibit-copy"><p className="eyebrow">MASTER MOTIF PROGRESSION</p><h3>Visual Evolution</h3><p>Primary-source tattoo records documenting Water/Fish, Butterfly/Roses, Hourglass, Ariel/Mirror, and Cosmic/Galaxy chronology.</p><div className="visdoc-absorbed"><strong>Integrated Records</strong>Water / Fish · Hourglass · Butterfly / Roses · Ariel / Mirror · Cosmic / Galaxy · Cosmic Spiral · Handless Clock</div><div className="visdoc-status matched">SOURCE MATCHED →</div></div></Link>
    <div className="visdoc-grid" style={{ marginTop: "1.25rem" }}><Link to="/media/death-of-deceit" className="visdoc-exhibit-card"><p className="eyebrow">CONCEPT ART</p><h3>Death of Deceit</h3><p>Pre-May 23, 2026 tattoo concept. Source record is complete; image waits for the supplied PNG to come through.</p><PendingAsset label="Death of Deceit concept" detail="Death of Deceit Tattoo Concept Pre May 23.png" /></Link><Link to="/media/raven-motif" className="visdoc-exhibit-card"><p className="eyebrow">SYMBOL / MOTIF</p><h3>Raven Motif</h3><p>Recurring raven imagery across artwork, tattoo documentation, lyrics, and visual identity.</p><div className="visdoc-status">UNDER RESTORATION</div></Link></div>
    <div className="visdoc-tier-label"><p className="eyebrow">SYMBOL DEVELOPMENT & SYSTEM INTEGRATION</p><h2>Interpretation Records</h2></div>
    <div className="visdoc-grid"><Link to="/media/omega-development" className="visdoc-exhibit-card"><p className="eyebrow">SYMBOL DEVELOPMENT</p><h3>Omega Development</h3><p>Early ring/circle attempts, early eight-spoke investigation, later Omega/fracture integration.</p><PendingAsset label="Omega reference graphics" detail="THE OMEGA and OMEGA MARK are awaiting the supplied reference files." /><div className="visdoc-status">SOURCE GRAPHICS PENDING</div></Link><Link to="/media/recurring-symbols" className="visdoc-exhibit-card"><p className="eyebrow">CROSS REFERENCE / SYSTEM INTEGRATION</p><h3>Recurring Symbols</h3><p>Observed recurrences and later system comparison, with the Vault System graphic kept here rather than in Visual Evolution.</p><PendingAsset label="Character dossier cards" detail="DMONIX Omega and Gizzy Graves α dossier cards are awaiting the supplied JPG files." /><div className="visdoc-status">SYSTEM GRAPHICS PENDING</div></Link></div>
    <div className="visdoc-grid" style={{ marginTop: "1.25rem" }}><Link to="/media/dmonix-tattoo-record" className="visdoc-exhibit-card"><p className="eyebrow">TATTOO / MOTIF RECORD</p><h3>DMONIX / Jerry Tattoo Motif Record</h3><p>One consolidated record for the nine documented tattoo motifs, not nine separate public cards.</p><PendingAsset label="Nine tattoo source images" detail="All-seeing eye, Anubis, beetle with sphere, diamond/star, fish/waves, flame, chained mummy, one-eyed skull, and spiral/spears are awaiting the supplied source files." /><div className="visdoc-status">SOURCE IMAGES PENDING</div></Link></div>
    <div className="visdoc-methodology"><p className="eyebrow">ARCHIVAL METHODOLOGY</p><h2>Restoration ongoing.</h2><p>Dates, provenance, and meaning remain limited to what the source records establish. Hourglass and Ariel/Mirror mappings stay flagged where the archive marks them uncertain.</p></div>
  </div></section>;
}
